# Generated by Django 3.0.3 on 2020-03-04 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_kakao_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='kakao_id',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
