# Generated by Django 3.0.3 on 2020-03-05 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_user_kakao_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='first_name',
            new_name='firstName',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='last_name',
            new_name='lastName',
        ),
    ]
