# Generated by Django 3.0.3 on 2020-03-16 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_user_google_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='google_id',
        ),
    ]
