# Generated by Django 3.0.3 on 2020-03-16 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='season',
            table='seasons',
        ),
    ]
