# Generated by Django 3.0.3 on 2020-03-03 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='color',
        ),
        migrations.RemoveField(
            model_name='product',
            name='dietary_fiber',
        ),
        migrations.RemoveField(
            model_name='product',
            name='thumbnail_url',
        ),
        migrations.RemoveField(
            model_name='product',
            name='total_fat',
        ),
        migrations.RemoveField(
            model_name='product',
            name='wood_type',
        ),
        migrations.AddField(
            model_name='product',
            name='big_image1',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='big_image2',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='big_image3',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='discount_rate',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='fat',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='small_image',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='carbonydrate',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='energy',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_in_stock',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.RemoveField(
            model_name='product',
            name='mineral',
        ),
        migrations.AddField(
            model_name='product',
            name='mineral',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='protein',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.RemoveField(
            model_name='product',
            name='vitamin',
        ),
        migrations.AddField(
            model_name='product',
            name='vitamin',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
