# Generated by Django 3.0.3 on 2020-02-29 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20200229_0646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_in_stock',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
