# Generated by Django 3.0.3 on 2020-03-02 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20200229_1255'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_by', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'sorts',
            },
        ),
        migrations.RenameField(
            model_name='bundle',
            old_name='is_main',
            new_name='is_in_promotion',
        ),
        migrations.AddField(
            model_name='recommendation',
            name='is_on_display',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='recipe',
            field=models.ManyToManyField(through='products.RecipeRecommendation', to='products.Recipe'),
        ),
    ]
