# Generated by Django 3.0.3 on 2020-03-02 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20200302_0827'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sort',
            old_name='sort_by',
            new_name='keyword',
        ),
    ]
