# Generated by Django 3.0.3 on 2020-03-02 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20200302_0847'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='big_image',
            new_name='big_image1',
        ),
        migrations.AddField(
            model_name='product',
            name='big_image2',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='big_image3',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
